### ISSUE TITLE
Dead links

### ISSUE THREAD

**Issue by JimmyTron** [kherld-hussein/tknp#2]
the portal link is inactive
the events link is also inactive
downloads link is inactive
hostel link is inactive
webpage link is inactive
for the webpage i suggest you redirect to the main website

**Comment by kherldhussein** [comment]
on It!

**Comment by kherldhussein** [comment]
Hi @JimmyTron  
I've already resolve the issue you can check out the new version

**Comment by kherldhussein** [comment]
I feel safe to close this issue, if you disagree please write in the comments and I will reopen it.
Thank you
